### ISSUE TITLE
"syntax error: invalid arithmetic operator" in log after `npm publish`

### ISSUE THREAD

**Issue by mbtools** [npm/template-oss#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Release Integration > Publish" action includes the `npm publish` command. The corresponding action log contains the following error:

```
/home/runner/work/_temp/570d07ac-66bd-47e2-805d-030313533c8a.sh: line 14: [[: + semver@7.6.0
0: syntax error: invalid arithmetic operator (error token is "@7.6.0
0")
```

Example: 

https://github.com/npm/node-semver/actions/runs/7788106733/job/21236934252

![image](https://github.com/npm/node-semver/assets/59966492/5b0df912-8db6-41a1-b441-21cfd12ad295)

### Expected Behavior

No error in log

### Steps To Reproduce

Run "Release Integration > Publish" workflow

https://github.com/npm/node-semver/blob/main/.github/workflows/release-integration.yml

### Environment

- github.com

**Comment by lukekarrys** [comment]
Good catch! We are trying to run `npm publish` and log the output but only return the exit code from a bash function. The rest of the output is being returned from the function as well, and that's what bash is erroring on.

Right now I think even if `npm publish` were to fail, this works as expected because there won't be anything on stdout in that case. But we should still clean up this script so it doesnt report those syntax errors.
